### ISSUE TITLE
GPS Signal not found 解决方法

### ISSUE THREAD

**Issue by mail2chensh** [youngshook/PokemonHook#3]
建议直接运行“start”方法，不要运行“startUpdating”，这样一般就不会提示“GPS Signal not found”

**Comment by soffchen** [comment]
确认好使，感谢

**Comment by soffchen** [comment]
呃，还是会出现这个错误，但是少了很多， 也不影响人物移动。

**Comment by youngshook** [comment]
@mail2chensh 👍
